### ISSUE TITLE
"Unable to authenticate to HE DNS" when using a password with signs

### ISSUE THREAD

**Issue by Inlifeuser** [tsaaristo/certbot-dns-he#1]
With this password I can log in to the HE account from a web browser, the problem was temporarily solved by changing the password to the one that does not contain signs.
In my case, that password contained the signs &, # and @.

```
$ sudo certbot certonly \
>   -a certbot-dns-he:dns-he --certbot-dns-he:dns-he-propagation-seconds 30 \
>   --certbot-dns-he:dns-he-credentials /home/[USERNAME]/dns_he.ini -d '[DOMAIN],*.[DOMAIN]' \
>   --server https://acme-v02.api.letsencrypt.org/directory --agree-tos \
>   --manual-public-ip-logging-ok --preferred-challenges dns -m [EMAIL]
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator certbot-dns-he:dns-he, Installer None
Obtaining a new certificate
Performing the following challenges:
dns-01 challenge for [DOMAIN]
dns-01 challenge for [DOMAIN]
Cleaning up challenges
Encountered exception during recovery: 
Traceback (most recent call last):                                                      
  File "/usr/lib/python3/dist-packages/certbot/auth_handler.py", line 75, in handle_authorizations                                                                              
    resp = self._solve_challenges(aauthzrs)                                             
  File "/usr/lib/python3/dist-packages/certbot/auth_handler.py", line 139, in _solve_challenges                                                                                 
    resp = self.auth.perform(all_achalls)                                               
  File "/usr/lib/python3/dist-packages/certbot/plugins/dns_common.py", line 57, in perform                                                                                      
    self._perform(domain, validation_domain_name, validation)                           
  File "/usr/local/lib/python3.7/dist-packages/certbot_dns_he/dns_he.py", line 59, in _perform                                                                                  
    raise errors.PluginError('Unable to authenticate to HE DNS')                        
certbot.errors.PluginError: Unable to authenticate to HE DNS                            

During handling of the above exception, another exception occurred:                     

Traceback (most recent call last):                                                      
  File "/usr/lib/python3/dist-packages/certbot/error_handler.py", line 108, in _call_registered                                                                                 
    self.funcs[-1]()                                                                    
  File "/usr/lib/python3/dist-packages/certbot/auth_handler.py", line 323, in _cleanup_challenges                                                                               
    self.auth.cleanup(achalls)                                                          
  File "/usr/lib/python3/dist-packages/certbot/plugins/dns_common.py", line 76, in cleanup                                                                                      
    self._cleanup(domain, validation_domain_name, validation)                           
  File "/usr/local/lib/python3.7/dist-packages/certbot_dns_he/dns_he.py", line 88, in _cleanup                                                                                  
    raise errors.PluginError('Unable to authenticate to HE DNS')                        
certbot.errors.PluginError: Unable to authenticate to HE DNS                            
Unable to authenticate to HE DNS
```

**Comment by gabb1** [comment]
if you quote the password it will work no need to change it
